version: '3.8'

services:
  catlow-yarns-sale:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catlow-yarns-gotland-sale
    ports:
      - "3000:80"  # Maps to port 3000 so your nginx can reverse proxy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - default

networks:
  default:
    external: false